[application]
name = "ProxyNexus"

[bundle]
identifier = "net.proxynexus.desktop"
icon = [
    "assets/icon.png",
    "assets/icon.ico",
    "assets/icon.icns"
]

[web.app]

# HTML title tag content
title = "Proxy Nexus"

# include `assets` in web platform
[web.resource]

# Additional CSS style files
style = []

# Additional JavaScript files
script = []

[web.resource.dev]

# JavaScript code file
# serve: [dev-server] only
script = []
